name: "ci-pilot-stage-release"
description: Tags branches when a comment is left on a PR
author: Jamie Halvorson <jamie@halvorson.co.uk>
inputs:
  dev_mode:
    description: "run the action in development mode"
    required: false
    default: "false"
  token:
    description: 'The GitHub authentication token'
    default: ${{ github.token }}
    required: true
  body:
    description: 'The contents of the comment.'
    required: true
outputs:
  comment_body:
    description: "the comment left on the PR"
runs:
  using: "node12"
  main: "dist/index.js"
