name: "test"
on:
  pull_request:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          dev_mode: "true"
          token: "${{ secrets.GITHUB_TOKEN }}"
